name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: node:10.16-jessie
      env:
        TF_VAR_account_id: ${{ secrets.ACCOUNT_ID }}
        TF_VAR_aws_access_key: ${{ secrets.ACCESS_KEY }}
        TF_VAR_aws_secret_key: ${{ secrets.SECRET_KEY }}
    steps:
    - uses: actions/checkout@v2
    - name: Set directory
      run: |
        echo $TF_VAR_account_id
        apt-get update
        apt-get install -y zip
        cd modules/lambda/app
        npm install --only=production
        npm run zip
    - uses: actions/upload-artifact@master
      with:
        name: lambda.zip
        path: modules/lambda/app/
  execute:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with:
        name: lambda.zip
        path: modules/lambda/app/
    - name: Terraform Init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: 'init'
      env:
        TF_VAR_account_id: ${{ secrets.ACCOUNT_ID }}
        TF_VAR_aws_access_key: ${{ secrets.ACCESS_KEY }}
        TF_VAR_aws_secret_key: ${{ secrets.SECRET_KEY }}
    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: 'apply'
        args: '-var-file="test.tfvars"'
      env:
        TF_VAR_account_id: ${{ secrets.ACCOUNT_ID }}
        TF_VAR_aws_access_key: ${{ secrets.ACCESS_KEY }}
        TF_VAR_aws_secret_key: ${{ secrets.SECRET_KEY }}